### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by 21salvador86** [vagonbar/gr-gwn3#1]
no module named libgwn problem in gnuradio 3.9

how can I solve

**Comment by vagonbar** [comment]
libgwn is part of this gr-gwn3 project, you can find is as a directory in the project..
Sorry I did not see issue before.

**Comment by salvador2186** [comment]
there is still same problem. What is the solution

**Comment by vagonbar** [comment]
libgwn is NOT part of GNU Radio, but of the gr-gwn3 project. Please open in your browser the project site, https://github.com/vagonbar/gr-gwn3. There you will see a directory named "libgwn"; this directory contains the library. Alternatively, clone the project, and in the directory where you cloned the project you will find a directory gr-gwn3/libgwn which contains the library.
